// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@basic-video-stream/log', 0],
  [0, '@basic-video-stream/log'],
  ['@basic-video-stream/reset', 1],
  [1, '@basic-video-stream/reset'],
  ['@basic-video-stream/start', 2],
  [2, '@basic-video-stream/start'],
  ['@basic-video-stream/videos', 3],
  [3, '@basic-video-stream/videos'],
  ['@basic-video-stream/add-video', 4],
  [4, '@basic-video-stream/add-video'],
  ['@basic-video-stream/messages', 5],
  [5, '@basic-video-stream/messages'],
  ['@basic-video-stream/add-message', 6],
  [6, '@basic-video-stream/add-message']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@basic-video-stream/log', getEncoding('@basic-video-stream/log')],
      ['@basic-video-stream/reset', c.bool],
      ['@basic-video-stream/start', c.string],
      ['@basic-video-stream/videos', getEncoding('@basic-video-stream/videos')],
      ['@basic-video-stream/add-video', getEncoding('@basic-video-stream/add-video')],
      ['@basic-video-stream/messages', getEncoding('@basic-video-stream/messages')],
      ['@basic-video-stream/add-message', getEncoding('@basic-video-stream/add-message')]
    ])
    this._responseEncodings = new Map([
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  log(args) {
    return this._callSync('@basic-video-stream/log', args)
  }

  reset(args) {
    return this._callSync('@basic-video-stream/reset', args)
  }

  start(args) {
    return this._callSync('@basic-video-stream/start', args)
  }

  videos(args) {
    return this._callSync('@basic-video-stream/videos', args)
  }

  addVideo(args) {
    return this._callSync('@basic-video-stream/add-video', args)
  }

  messages(args) {
    return this._callSync('@basic-video-stream/messages', args)
  }

  addMessage(args) {
    return this._callSync('@basic-video-stream/add-message', args)
  }

  onLog(responseFn) {
    this._handlers['@basic-video-stream/log'] = responseFn
  }

  onReset(responseFn) {
    this._handlers['@basic-video-stream/reset'] = responseFn
  }

  onStart(responseFn) {
    this._handlers['@basic-video-stream/start'] = responseFn
  }

  onVideos(responseFn) {
    this._handlers['@basic-video-stream/videos'] = responseFn
  }

  onAddVideo(responseFn) {
    this._handlers['@basic-video-stream/add-video'] = responseFn
  }

  onMessages(responseFn) {
    this._handlers['@basic-video-stream/messages'] = responseFn
  }

  onAddMessage(responseFn) {
    this._handlers['@basic-video-stream/add-message'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@basic-video-stream/log',
      '@basic-video-stream/reset',
      '@basic-video-stream/start',
      '@basic-video-stream/videos',
      '@basic-video-stream/add-video',
      '@basic-video-stream/messages',
      '@basic-video-stream/add-message'
    ].includes(command)
  }
}

export default HRPC
