// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @basic-video-stream/log
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.level)
    c.string.preencode(state, m.message)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.string.encode(state, m.level)
    c.string.encode(state, m.message)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      level: r0,
      message: r1,
      at: r2
    }
  }
}

// @basic-video-stream/writer
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @basic-video-stream/invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @basic-video-stream/video
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.json.preencode(state, m.blob)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.json.encode(state, m.blob)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      type: r2,
      blob: r3,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @basic-video-stream/videos
const encoding4 = c.array(c.frame(encoding3))

// @basic-video-stream/add-video
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.uri)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.string.encode(state, m.uri)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      name: r0,
      uri: r1
    }
  }
}

// @basic-video-stream/message
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @basic-video-stream/messages
const encoding7 = c.array(c.frame(encoding6))

// @basic-video-stream/add-message
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      text: r0,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@basic-video-stream/log':
      return encoding0
    case '@basic-video-stream/writer':
      return encoding1
    case '@basic-video-stream/invite':
      return encoding2
    case '@basic-video-stream/video':
      return encoding3
    case '@basic-video-stream/videos':
      return encoding4
    case '@basic-video-stream/add-video':
      return encoding5
    case '@basic-video-stream/message':
      return encoding6
    case '@basic-video-stream/messages':
      return encoding7
    case '@basic-video-stream/add-message':
      return encoding8
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
