// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@basic-chat-blind-peering/log', 0],
  [0, '@basic-chat-blind-peering/log'],
  ['@basic-chat-blind-peering/reset', 1],
  [1, '@basic-chat-blind-peering/reset'],
  ['@basic-chat-blind-peering/start', 2],
  [2, '@basic-chat-blind-peering/start'],
  ['@basic-chat-blind-peering/messages', 3],
  [3, '@basic-chat-blind-peering/messages'],
  ['@basic-chat-blind-peering/add-message', 4],
  [4, '@basic-chat-blind-peering/add-message'],
  ['@basic-chat-blind-peering/add-blind-peer', 5],
  [5, '@basic-chat-blind-peering/add-blind-peer']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@basic-chat-blind-peering/log', getEncoding('@basic-chat-blind-peering/log')],
      ['@basic-chat-blind-peering/reset', c.bool],
      ['@basic-chat-blind-peering/start', c.string],
      ['@basic-chat-blind-peering/messages', getEncoding('@basic-chat-blind-peering/messages')],
      ['@basic-chat-blind-peering/add-message', c.string],
      ['@basic-chat-blind-peering/add-blind-peer', c.string]
    ])
    this._responseEncodings = new Map([
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  log(args) {
    return this._callSync('@basic-chat-blind-peering/log', args)
  }

  reset(args) {
    return this._callSync('@basic-chat-blind-peering/reset', args)
  }

  start(args) {
    return this._callSync('@basic-chat-blind-peering/start', args)
  }

  messages(args) {
    return this._callSync('@basic-chat-blind-peering/messages', args)
  }

  addMessage(args) {
    return this._callSync('@basic-chat-blind-peering/add-message', args)
  }

  addBlindPeer(args) {
    return this._callSync('@basic-chat-blind-peering/add-blind-peer', args)
  }

  onLog(responseFn) {
    this._handlers['@basic-chat-blind-peering/log'] = responseFn
  }

  onReset(responseFn) {
    this._handlers['@basic-chat-blind-peering/reset'] = responseFn
  }

  onStart(responseFn) {
    this._handlers['@basic-chat-blind-peering/start'] = responseFn
  }

  onMessages(responseFn) {
    this._handlers['@basic-chat-blind-peering/messages'] = responseFn
  }

  onAddMessage(responseFn) {
    this._handlers['@basic-chat-blind-peering/add-message'] = responseFn
  }

  onAddBlindPeer(responseFn) {
    this._handlers['@basic-chat-blind-peering/add-blind-peer'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@basic-chat-blind-peering/log',
      '@basic-chat-blind-peering/reset',
      '@basic-chat-blind-peering/start',
      '@basic-chat-blind-peering/messages',
      '@basic-chat-blind-peering/add-message',
      '@basic-chat-blind-peering/add-blind-peer'
    ].includes(command)
  }
}

export default HRPC
